blank_issues_enabled: false
contact_links:
  - name: New Features ğŸš€
    url: https://github.com/iputapp/lounas/issues/new?assignees=&labels=&template=new.md&title=%5BNew%5D%3A+
    about: For developers ğŸ§
  - name: Issues to be fixed ğŸš‘
    url: https://github.com/iputapp/lounas/issues/new?assignees=&labels=&template=issue.md&title=%5BIssue%5D%3A+
    about: For developers ğŸ§
