blank_issues_enabled: false
contact_links:
  - name: Bug Report ğŸ
    url: https://github.com/wiyco/imap/issues/new?assignees=&labels=bug%2Ctriage&projects=4&template=bug-report.yml&title=%5BBug%5D%3A+
    about: ãƒã‚°å ±å‘Šãƒ•ã‚©ãƒ¼ãƒ  ğŸ˜
  - name: Tasks (Features) ğŸš€
    url: https://github.com/wiyco/imap/issues/new?assignees=&labels=&projects=4&template=task-feature.md&title=%5BFeature%5D%3A+
    about: For TEAM PIPLUP ğŸ§
