# https://github.com/marketplace/actions/discord-webhook-action

name: Discord Notify Deploy
on: deployment

jobs:
  discord-notify-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL_WORKFLOW }}
          embed-title: "ğŸ› ï¸ [${{ github.repository }}] Deploy ${{ github.event.deployment.environment }}"
          embed-description: "Repository: ${{ github.repository }}\nDeploy: ${{ github.event.deployment.environment }}\nStatus: ${{ job.status }} ${{ job.status == 'success' && 'âœ…' || job.status == 'failure' && 'ğŸ›‘' || 'ğŸŸ¨' }}\n${{github.event.deployment.description}}"
          embed-color: ${{ job.status == 'success' && '2278750' || job.status == 'failure' && '15680580' || '15381256' }}
          embed-author-icon-url: ${{ github.event.deployment.creator.avatar_url }}
          embed-author-name: ${{ github.event.deployment.creator.name }}
          embed-author-url: ${{ github.event.deployment.creator.html_url }}
          embed-url: ${{ github.event.deployment.url }}
