# https://github.com/marketplace/actions/discord-webhook-action

name: Discord Notify Deploy
on: deployment

jobs:
  discord-notify-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL_WORKFLOW }}
          embed-title: "[${{ github.repository }}] ğŸ› ï¸ Deploy ${{ github.event.deployment.environment }}"
          embed-description: "Target: ${{ github.repository }}/${{ github.event.workflow_run.head_branch }}\nDeploy: ${{ github.event.deployment.environment }} ${{ github.event.workflow_run.conclusion }}${{ job.status == 'success' && 'âœ…' || job.status == 'failure' && 'ğŸ›‘' || 'ğŸŸ¨' }}\nCreator: ${{ github.event.deployment.creator.name }}\n${{github.event.deployment.description}}"
          embed-color: ${{ job.status == 'success' && '2278750' || job.status == 'failure' && '15680580' || '15381256' }}
          embed-author-icon-url: ${{ github.event.deployment.creator.avatar_url }}
